name: Actualizacion Pronosticos IA

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar Requests
        run: pip install requests
      - name: Ejecutar Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: python auto_update.py
      - name: Guardar Cambios
        run: |
          git config --global user.name "IA-Bot"
          git config --global user.email "bot@pronosticos.com"
          if [ -f tips.json ]; then
            git add tips.json
            git commit -m "IA Update" || exit 0
            git push
          fi
